= 子网映射
:allow-uri-read: 




=== 子网映射

在此版本中，您可以使用子网映射以新的方式管理故障转移时的 IP 地址，这使您能够为每个 vCenter 添加子网。当您这样做时，您需要为每个虚拟网络定义 IPv4 CIDR、默认网关和 DNS。

故障转移时， NetApp Disaster Recovery通过查看为映射的虚拟网络提供的 CIDR 来确定每个 vNIC 的适当 IP 地址，并使用它来派生新的 IP 地址。

例如：

* 网络A = 10.1.1.0/24
* 网络B = 192.168.1.0/24


VM1 有一个连接到 NetworkA 的 vNIC（10.1.1.50）。在复制计划设置中，NetworkA 映射到 NetworkB。

故障转移时， NetApp Disaster Recovery会替换原始 IP 地址 (10.1.1) 的网络部分，并保留原始 IP 地址 (10.1.1.50) 的主机地址 (.50)。对于 VM1， NetApp Disaster Recovery查看 NetworkB 的 CIDR 设置，并使用 NetworkB 网络部分 192.168.1，同时保留主机部分 (.50) 来为 VM1 创建新的 IP 地址。新的IP变为192.168.1.50。

总之，主机地址保持不变，而网络地址则被站点子网映射中配置的地址替换。这使您能够更轻松地管理故障转移时的 IP 地址重新分配，特别是当您需要管理数百个网络和数千个虚拟机时。

有关在站点中包含子网映射的详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["添加 vCenter 服务器站点"]。



=== 跳过保护

您现在可以跳过保护，以便服务在复制计划故障转移后不会自动创建反向保护关系。如果您希望在NetApp Disaster Recovery中将恢复的站点恢复在线之前对其执行其他操作，这将非常有用。

当您启动故障转移时，如果原始源站点处于在线状态，则默认情况下服务会自动为复制计划中的每个卷创建反向保护关系。这意味着该服务创建从目标站点到源站点的SnapMirror关系。当您启动故障恢复时，该服务还会自动逆转SnapMirror关系。

启动故障转移时，您现在可以选择“跳过保护”选项。这样，服务就不会自动逆转SnapMirror关系。相反，它将可写卷留在复制计划的两侧。

原始源站点恢复在线后，您可以通过从复制计划操作菜单中选择*保护资源*来建立反向保护。这会尝试为计划中的每个卷创建反向复制关系。您可以重复运行此作业，直到恢复保护。当保护恢复后，您可以按照通常的方式启动故障恢复。

有关跳过保护的详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["将应用程序故障转移到远程站点"]。



=== 复制计划中的SnapMirror计划更新

NetApp Disaster Recovery现在支持使用外部快照管理解决方案，例如本机ONTAP SnapMirror策略调度程序或与ONTAP 的第三方集成。如果复制计划中的每个数据存储库（卷）都已具有在其他地方管理的SnapMirror关系，则可以将这些快照用作NetApp Disaster Recovery中的恢复点。

要进行配置，请在复制计划 > 资源映射部分中，在配置数据存储映射时选中 *使用平台管理的备份和保留计划* 复选框。

选择该选项后， NetApp Disaster Recovery不会配置备份计划。但是，您仍然需要配置保留计划，因为仍可能需要拍摄快照以进行测试、故障转移和故障回复操作。

配置完成后，服务不会定期拍摄任何快照，而是依赖外部实体来拍摄和更新这些快照。

有关在复制计划中使用外部快照解决方案的详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。
