---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: 使用 Amazon EVS 和Amazon FSx for NetApp ONTAP介绍NetApp Disaster Recovery。 
---
= 了解结合使用 Amazon Elastic VMware Service 和 Amazon FSx for NetApp ONTAP 的 NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery 通过将数据从本地环境复制到 Amazon EVS 和 Amazon FSx for NetApp ONTAP，帮助保护 VMware 工作负载以实现灾难恢复。

任何 DR 解决方案面临的主要挑战之一是管理购买、配置和维护额外计算、网络和存储资源的增量成本，以提供 DR 复制和恢复基础设施。保护关键内部虚拟资源的一个流行选择是使用云托管虚拟资源作为 DR 复制和恢复基础设施。亚马逊就是此类解决方案的一个例子，它可以提供与NetApp ONTAP托管 VM 基础架构兼容的经济高效的资源。

亚马逊推出了 Amazon Elastic VMware Service (Amazon EVS)，可在您的虚拟私有云 (VPC) 中启用 VMware Cloud Foundation。Amazon EVS 提供 AWS 的弹性和性能以及熟悉的 VMware 软件和工具，使 Amazon EVS vCenters 能够与您的本地虚拟化基础架构集成。

虽然 Amazon EVS 附带了内置存储资源，但使用本机存储可能会降低其对存储密集型工作负载组织的有效性。在这些情况下，将 Amazon EVS 与 Amazon FSx for NetApp ONTAP 存储（Amazon FSxN）结合使用可以提供更灵活的存储解决方案。此外，当您在本地使用 NetApp ONTAP 存储解决方案托管 VMware 基础架构时，将 Amazon EVS 与 FSx for ONTAP 结合使用可在本地和云环境中提供数据互操作性和保护功能。

有关Amazon FSx for NetApp ONTAP 的信息，请参阅 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSx for NetApp ONTAP入门"^]。
