---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: NetApp Console 代理协调 NetApp Console 与云或本地存储资源之间的连接和管理。 
---
= 安装用于NetApp Disaster Recovery的NetApp Console代理
:allow-uri-read: 


[role="lead"]
NetApp Console 代理使您能够将 NetApp Console 部署连接到基础架构，以便在 AWS、Azure、Google Cloud 或本地环境中安全地编排解决方案。Console 代理执行 NetApp Console 需要执行的操作，以管理您的数据基础架构。Console 代理会不断轮询 NetApp Disaster Recovery 软件作为服务层，以了解需要采取的任何操作。

对于 NetApp Disaster Recovery，执行的操作使用每个相应服务的本机 API 来协调 VMware vCenter 群集和 ONTAP 存储实例，以便为在本地位置运行的生产虚拟机提供保护。虽然可以在任何网络位置安装 Console 代理，但建议您在灾难恢复站点中安装 Console 代理以进行 NetApp Disaster Recovery。在 DR 站点中安装可确保在主站点发生故障时，NetApp 控制台 UI 保持与 Console 代理的连接，并可以在该 DR 站点中协调恢复过程。



== 安装

* 要使用 Disaster Recovery，请在标准模式下安装 Console 代理。要了解有关 Console 代理安装类型的更多信息，请访问 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["了解 NetApp Console 部署模式"^]。


Console 代理的具体安装步骤取决于您的部署类型。有关详细信息，请参见 link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["了解控制台代理"^]。


TIP: 使用 Amazon AWS 安装 Console 代理的最简单方法是使用 AWS Marketplace。有关使用 AWS Marketplace 安装 Console 代理的详细信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["从 AWS Marketplace 创建 Console 代理"^]。
