---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter,amazon elastic vmware service 
summary: 使用 Amazon EVS 和Amazon FSx for NetApp ONTAP介绍NetApp灾难恢复。 NetApp灾难恢复是一种许可产品，必须先购买才能使用。有多种类型的许可证，并且您可以通过多种方式购买许可证。 
---
= 将NetApp灾难恢复服务添加到您的 Amazon EVS NetApp控制台帐户
:allow-uri-read: 


[role="lead"]
NetApp灾难恢复是一种许可产品，必须先购买才能使用。有多种类型的许可证，并且您可以通过多种方式购买许可证。许可证授权您在特定时间段内保护特定数量的数据。

有关NetApp灾难恢复许可证的更多信息，请参阅link:../get-started/dr-licensing.html["设置NetApp灾难恢复许可"]。



== 许可证类型

许可证主要有两种类型：

* NetApp提供link:../get-started/dr-licensing.html["30天试用许可证"]您可以使用它来评估使用ONTAP和 VMware 资源的NetApp灾难恢复。此许可证提供 30 天的使用期限，不受限制地使用受保护的容量。
* 如果您希望在 30 天试用期之后获得 DR 保护，请购买生产许可证。您可以通过任何 NetApp 云合作伙伴的市场购买此许可证，但对于本指南，我们建议您使用 Amazon AWS Marketplace 购买NetApp Disaster Recovery 的市场许可证。要了解有关通过 Amazon Marketplace 购买许可证的更多信息，请参阅link:../get-started/dr-licensing.html["通过 AWS Marketplace 订阅"]。




== 确定灾难恢复容量需求

在购买许可证之前，您应该了解需要保护多少ONTAP存储容量。使用NetApp ONTAP存储的优势之一是NetApp存储数据的效率很高。  ONTAP卷中存储的所有数据（例如托管虚拟机的 VMware 数据存储区）都是以高效的方式存储的数据。 ONTAP在将数据写入物理存储时默认采用三种存储效率：压缩、重复数据删除和压缩。最终结果是存储效率在 1.5:1 到 4:1 之间，具体取决于所存储的数据类型。事实上， NetApp提供了 https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["存储效率保证"^]对于某些工作负载。

这对您有利，因为在应用所有ONTAP存储效率之后， NetApp Disaster Recovery 会计算许可容量。例如，假设您在 vCenter 中配置了一个 100 TB (TiB) NFS 数据存储区来托管您想要使用该服务保护的 100 台虚拟机。此外，假设当数据写入ONTAP卷时，自动应用的存储效率技术会导致这些虚拟机仅消耗 33TiB（3：1 的存储效率）。 NetApp灾难恢复仅需要获得 33TiB 的许可，而不是 100TiB。与其他 DR 解决方案相比，这对于您的 DR 解决方案的总体拥有成本来说是一个非常大的好处。

.步骤
. 要确定托管要保护的 VMware 数据存储库的每个卷上消耗的数据量，请通过对每个卷运行ONTAP CLI 命令来确定磁盘容量消耗： `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` 。
+
例如：

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. 注意每个卷的“总物理使用量”值。这是NetApp灾难恢复需要保护的数据量，也是您将用来确定需要许可多少容量的值。

