---
sidebar: sidebar 
permalink: reference/vcenter-privileges.html 
keywords: disaster recovery, bluexp, vcenter, 
summary: 'vCenter 帐户必须具有一组最低限度的 vCenter 权限，以允许NetApp Disaster Recovery 执行其服务，例如注册和取消注册数据存储库、启动和停止虚拟机以及重新配置虚拟机 (VM)。下表列出了NetApp灾难恢复与 vCenter 集群连接所需的所有权限。' 
---
= NetApp灾难恢复所需的 vCenter 权限
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
vCenter 帐户必须具有一组最低限度的 vCenter 权限，以允许NetApp Disaster Recovery 执行其服务，例如注册和取消注册数据存储库、启动和停止虚拟机以及重新配置虚拟机 (VM)。下表列出了NetApp灾难恢复与 vCenter 集群连接所需的所有权限。

[cols="25,35a,40a"]
|===
| 类型 | 权限名称 | 描述 


| *数据存储*  a| 
数据存储.配置数据存储
 a| 
用于配置数据存储。



|   a| 
数据存储. 删除数据存储
 a| 
用于删除数据存储。



| 虚拟机  a| 
虚拟机. 配置. 更改设置
 a| 
用于更改常规 VM 设置。



|   a| 
虚拟机. 配置. 修改设备设置
 a| 
用于更改现有设备的属性。



|   a| 
虚拟机.配置.从路径重新加载
 a| 
用于更改 VM 配置补丁，同时保留 VM 的身份。  VMware vCenter Site Recovery Manager 等解决方案使用此操作在故障转移和故障恢复期间维护 VM 标识。



|   a| 
虚拟机. 配置. 重命名
 a| 
用于重命名虚拟机或修改虚拟机的关联节点。



|   a| 
虚拟机. 配置. 重置客户机信息
 a| 
用于编辑 VM 的客户操作系统信息。



|   a| 
虚拟机. 配置. 更改内存
 a| 
用于更改分配给 VM 的内存量。



|   a| 
虚拟机. 配置. 更改 CPU 数量
 a| 
用于更改虚拟 CPU 的数量。



| *虚拟机客户机*  a| 
虚拟机.客户机操作.客户机操作修改
 a| 
启用涉及对 VM 中的客户操作系统进行更改的 VM 客户操作，例如将文件传输到 VM。



| *虚拟机交互*  a| 
虚拟机.交互.关闭
 a| 
用于关闭已启动的虚拟机。此操作将关闭客户操作系统。



|   a| 
虚拟机.交互.开启
 a| 
用于启动已关闭的虚拟机并恢复已挂起的虚拟机。



|   a| 
虚拟机.交互.VMware Tools 安装
 a| 
用于将 VMware Tools CD 安装程序作为客户操作系统的 CD-ROM 进行挂载和卸载。



| *虚拟机清单*  a| 
虚拟机. 清单. 新建
 a| 
用于创建虚拟机并为其执行分配资源。



|   a| 
虚拟机.库存.注册
 a| 
用于将现有 VM 添加到 vCenter Server 或主机清单。



|   a| 
虚拟机. 清单. 取消注册
 a| 
用于从 vCenter Server 或主机清单中取消注册虚拟机。



| *虚拟机状态*  a| 
虚拟机. 快照管理. 创建快照
 a| 
用于从 VM 的当前状态创建快照。



|   a| 
虚拟机. 快照管理. 删除快照
 a| 
用于从快照历史记录中删除快照。



|   a| 
虚拟机. 快照管理. 恢复到快照
 a| 
用于将 VM 设置为给定快照时的状态。

|===